category = "Certificates of Deposit (CDs)"

categoryInfo = """
Certificates of Deposit (CDs) are a type of time deposit offered by banks and credit unions that provide a fixed interest rate over a specified term. They represent a commitment by the depositor to keep their money in the account for a set period, which typically ranges from as short as one month to as long as ten years. During this time, the financial institution pays the depositor interest at an agreed-upon rate.

One of the primary advantages of CDs is that they often offer higher interest rates compared to regular savings accounts or checking accounts. This is because the funds are locked in for the duration of the term, and the institution can use the money for longer-term investments or lending activities. However, this locking mechanism means that the funds are not easily accessible during the term without incurring a penalty for early withdrawal. The penalty could be a loss of interest or even part of the principal, depending on the terms of the specific CD.

The terms for CDs vary, with common durations including 6 months, 1 year, 3 years, 5 years, and even up to 10 years. The longer the term, the higher the potential interest rate, but this also increases the risk of not being able to access funds if an emergency arises. The interest earned on a CD can be compounded periodically (such as monthly or annually) or paid out at maturity, depending on the bank or credit union’s specific terms. If compounded, the interest is added to the principal, and future interest is earned on the new balance.

CDs are generally considered a low-risk investment since they are backed by the Federal Deposit Insurance Corporation (FDIC) in the United States. The FDIC insures up to $250,000 per depositor, per bank, offering peace of mind to investors who choose this type of financial product. This makes CDs a safer option for individuals looking to protect their principal while earning a steady return.

One popular strategy for managing the balance between liquidity and interest rate exposure is known as a “CD ladder.” In this strategy, an investor opens multiple CDs with staggered maturity dates. For example, they might invest in CDs with terms of 1 year, 3 years, 5 years, etc. When one CD matures, the investor can reinvest the principal and interest into a new CD, potentially at a higher interest rate if rates have risen, while maintaining some access to their funds at regular intervals.

At the end of a CD’s term, the depositor is typically presented with two options: to withdraw the principal and accumulated interest or to roll the funds into a new CD with a similar or different term. This provides some flexibility, although the funds remain tied up for the new term if reinvested.

However, it's important to note that CDs are not a suitable option for funds that may need to be accessed quickly or unexpectedly. Since early withdrawals often result in penalties and because the funds are locked for a set period, CDs are not ideal for emergency savings or short-term liquidity needs. Investors who choose to invest in CDs should be confident that they will not need access to the funds before the CD matures to avoid the penalty fees that could reduce their returns.
"""

learnMore = '''
A Certificate of Deposit (CD) is a savings account offered by banks that provides a fixed interest rate for a specified term. Early withdrawal typically incurs a penalty.
(We should add more here)
'''
image = "cdImage.jpg"

[[questions]]
question = "What is a Certificate of Deposit (CD)?"
choices = [
"An investment that provides a fixed interest rate for a set period of time",
"A type of savings account with no interest",
"A short-term loan to the bank",
"A bond issued by the government"
]
answer = "An investment that provides a fixed interest rate for a set period of time"
why = "A CD is a time deposit offered by banks that pays a fixed interest rate for a predetermined term."
difficulty = "easy"
reward = 100

[[questions]]
question = "What happens if you withdraw money from a CD before its maturity date?"
choices = [
"You may face an early withdrawal penalty",
"You can withdraw without any penalty",
"You get a higher interest rate",
"The interest rate is reduced"
]
answer = "You may face an early withdrawal penalty"
why = "Withdrawing funds before the maturity date of a CD usually results in a penalty, which can affect both the principal and interest earned."
difficulty = "medium"
reward = 200

[[questions]]
question = "What is the typical term length for a CD?"
choices = [
"1 month to 10 years",
"1 year to 5 years",
"1 week to 3 months",
"1 day to 1 year"
]
answer = "1 month to 10 years"
why = "CDs can have terms ranging from as short as one month to as long as 10 years, though terms of 1 year to 5 years are common."
difficulty = "medium"
reward = 150

[[questions]]
question = "What is the primary risk of investing in a CD?"
choices = [
"Risk of early withdrawal penalties",
"Risk of interest rate fluctuations",
"Risk of default by the bank",
"Risk of inflation"
]
answer = "Risk of early withdrawal penalties"
why = "The main risk associated with CDs is the penalty for early withdrawal, which can reduce the return on investment."
difficulty = "medium"
reward = 250

[[questions]]
question = "How do interest rates on CDs compare to regular savings accounts?"
choices = [
"CD interest rates are typically higher",
"CD interest rates are typically lower",
"CD interest rates are the same",
"CDs have no interest"
]
answer = "CD interest rates are typically higher"
why = "CDs generally offer higher interest rates than regular savings accounts in exchange for locking up the funds for a fixed period."
difficulty = "easy"
reward = 100

[[questions]]
question = "What is a CD ladder?"
choices = [
"A strategy for withdrawing money early without penalty",
"A strategy for diversifying interest rates by having multiple CDs with different maturity dates",
"A type of CD with no interest rate",
"A way to avoid inflation"
]
answer = "A strategy for diversifying interest rates by having multiple CDs with different maturity dates"
why = "A CD ladder is a strategy where you invest in several CDs with different maturity dates, allowing for periodic access to funds and potentially higher overall returns."
difficulty = "hard"
reward = 400

[[questions]]
question = "Can you access your funds in a CD anytime?"
choices = [
"Yes, but there may be a penalty",
"No, the funds are locked until maturity",
"Yes, with no penalty",
"Only on specific dates"
]
answer = "No, the funds are locked until maturity"
why = "The funds in a CD are typically locked until the maturity date, and early withdrawal may result in penalties."
difficulty = "medium"
reward = 200

[[questions]]
question = "What happens at the end of a CD’s term?"
choices = [
"The principal and interest are withdrawn automatically",
"The principal is reinvested into a new CD",
"It is renewed at a lower interest rate",
"The funds remain in the account indefinitely"
]
answer = "The principal and interest are withdrawn automatically"
why = "At the end of the term, the CD typically matures, and the principal along with any earned interest is either paid out or rolled into a new CD, depending on the account terms."
difficulty = "medium"
reward = 150

[[questions]]
question = "What is the Federal Deposit Insurance Corporation (FDIC)?"
choices = [
"A government agency that insures bank deposits",
"A bank that sells CDs",
"A type of interest rate on a CD",
"A tool for calculating CD returns"
]
answer = "A government agency that insures bank deposits"
why = "The FDIC insures bank deposits up to $250,000 per depositor, providing protection against bank failure."
difficulty = "easy"
reward = 100

[[questions]]
question = "Which of the following is true about interest on CDs?"
choices = [
"Interest is always paid monthly",
"Interest can be compounded or paid at maturity depending on the CD",
"Interest is paid daily",
"Interest is taxed at a higher rate"
]
answer = "Interest can be compounded or paid at maturity depending on the CD"
why = "CDs may offer interest that is either compounded periodically or paid out at the time of maturity. The specific terms depend on the CD agreement."
difficulty = "easy"
reward = 100
