category = "Example Category"

categoryInfo = "Here is a description of the question category"

learnMore = '''
We could put learning information here

or in a different format if needed
'''
image = "lifeInvestIcon.png"
[[questions]]
question = "What does 'IPO' stand for?"

choices = [
"Initial Public Offering",
"Instant Purchase Order",
"Investment Portfolio Option",
"Internal Profit Objective"
]

answer = "Initial Public Offering"
why = 'IPO means "Initial Public Offering"'
difficulty = "easy"
reward = 100

[[questions]]
question = "If a stock splits 2-for-1, what happens to the share price (assuming all else equal)?"
choices = ["It doubles",
"It halves",
"It stays the same",
"It drops to zero"]
answer = "It halves"
why = "Stock splits increase the number of shares, but the value of the company stays the same, so the share price will be cut in half."
difficulty = "hard"
reward = 500
