[[goodEvents]]
eventDesc = "You hit it big in Vegas and won $5000!"
price = 5000

[[goodEvents]]
eventDesc = "A distant relative left you a generous inheritance."
price = 4000

[[goodEvents]]
eventDesc = "You sold an old collectible online for a high price."
price = 1200

[[goodEvents]]
eventDesc = "Your side hustle took off!"
price = 2000

[[goodEvents]]
eventDesc = "You received a government grant for your project."
price = 3500

[[goodEvents]]
eventDesc = "You won a community raffle."
price = 800

[[goodEvents]]
eventDesc = "Your investments performed exceptionally well."
price = 3000

[[goodEvents]]
eventDesc = "You found a rare coin while hiking."
price = 600

[[goodEvents]]
eventDesc = "You earned a bonus at work."
price = 1500

[[goodEvents]]
eventDesc = "You were overcharged last year and got a big tax refund."
price = 2500

[[neutralEvents]]
eventDesc = "You attended a local festival."
price = -100

[[neutralEvents]]
eventDesc = "You replaced your worn-out shoes."
price = -50

[[neutralEvents]]
eventDesc = "You donated a small amount to charity."
price = -75

[[neutralEvents]]
eventDesc = "You took a short vacation."
price = -300

[[neutralEvents]]
eventDesc = "You hosted a dinner party for friends."
price = -120

[[neutralEvents]]
eventDesc = "You upgraded your phone plan."
price = -60

[[neutralEvents]]
eventDesc = "You bought gifts for a friend's birthday."
price = -80

[[neutralEvents]]
eventDesc = "You helped a neighbor and got free baked goods."
price = 0

[[neutralEvents]]
eventDesc = "You spent a weekend binge-watching shows. No regrets."
price = 0

[[neutralEvents]]
eventDesc = "You tried a new hobby, bought some supplies."
price = -90

[[badEvents]]
eventDesc = "You fell down the stairs and broke your leg. Hospital fees!"
price = -5000

[[badEvents]]
eventDesc = "Your car broke down and needed major repairs."
price = -1800

[[badEvents]]
eventDesc = "You lost your phone and had to replace it."
price = -1000

[[badEvents]]
eventDesc = "You were scammed online."
price = -1500

[[badEvents]]
eventDesc = "Your pet got sick and needed urgent care."
price = -1200

[[badEvents]]
eventDesc = "Your basement flooded."
price = -2000

[[badEvents]]
eventDesc = "You broke a neighbor’s window playing catch."
price = -300

[[badEvents]]
eventDesc = "Your bike was stolen."
price = -450

[[badEvents]]
eventDesc = "You accidentally deleted important work and had to pay for recovery."
price = -700

[[badEvents]]
eventDesc = "You were fined for late loan payment."
price = -600
