category = "Stocks"

categoryInfo = """
The stock market is where people buy and sell ownership shares in companies, known as stocks or shares. When a company needs money to grow, it can offer shares to the public through an Initial Public Offering (IPO). This is the process where a company first sells its shares to investors, and after that, those shares can be traded on stock exchanges like the New York Stock Exchange (NYSE) or NASDAQ.

Key Concepts in the Stock Market
Stock Ownership: Each share you buy represents partial ownership in the company. If the company performs well, the stock price may rise, and you can make a capital gain when you sell your shares at a higher price.

Dividends: Some companies share their profits with shareholders in the form of dividends. These are payments made to investors, usually on a quarterly basis, and are one way to earn money from owning stocks.

Bull and Bear Markets:

A bull market happens when stock prices are generally rising, and investors are optimistic about the economy.

A bear market is the opposite, where stock prices are falling, and investors are more cautious or fearful.

Stock Splits: Sometimes, companies perform a stock split to make their shares more affordable. For example, a 2-for-1 stock split means you’ll get two shares for every one share you already own, but the price of each share will be halved. Your total investment value stays the same.

Price-to-Earnings (P/E) Ratio: This ratio helps investors determine if a stock is overvalued or undervalued. It’s calculated by dividing the stock’s current price by its earnings per share. A high P/E ratio might mean investors expect the company to grow a lot in the future, while a low P/E might suggest the stock is a bargain—or in trouble.

Market Capitalization (Market Cap): This is the total value of all of a company’s outstanding shares. To calculate market cap, multiply the stock price by the number of shares. Companies are often categorized as:

Large-cap: Big, established companies

Mid-cap: Moderate-sized companies

Small-cap: Smaller, higher-risk companies with more growth potential

Short Selling: This is a strategy where investors bet against a stock. They borrow shares, sell them, and then hope to buy them back at a lower price. While this can lead to profit if the stock price falls, it’s risky because if the stock price goes up, the investor will lose money.

Diversification: This is a risk management strategy where investors spread their money across different types of investments. By doing this, if one investment performs poorly, the others may perform better, reducing the overall risk.

Stock Trading: Stocks can be traded on exchanges. When investors buy or sell stocks, they do so through brokers or online trading platforms. Prices fluctuate based on demand and supply in the market.

Common Stock Market Terms
IPO (Initial Public Offering): The first sale of stock by a company to the public. This is how a company becomes publicly traded.

Capital Gain: The profit from selling a stock at a higher price than you bought it.

Dividend: A portion of a company's profits paid to shareholders, often quarterly.

P/E Ratio: The ratio of a company’s current stock price to its earnings per share. It helps investors evaluate a company’s stock.

Bull Market: A market where prices are rising or expected to rise.

Bear Market: A market where prices are falling or expected to fall.

Stock Split: A process where a company increases the number of shares and lowers the price per share, but your overall investment value remains the same.

Market Cap: The total value of a company’s outstanding shares, calculated by multiplying the stock price by the number of shares.

Short Selling: A strategy where investors borrow and sell a stock, hoping to buy it back at a lower price to profit from the price difference.

Diversification: Spreading investments across different sectors or asset types to reduce risk.

How Stocks Are Affected
The stock price of a company can rise or fall for many reasons. Good news about a company, such as strong earnings or new product launches, can cause its stock price to go up. On the other hand, negative news, like poor financial results or a product recall, can cause stock prices to fall.

Market Indices
To track the performance of the stock market, investors look at market indexes. One of the most well-known is the S&P 500, which tracks the stock prices of 500 large companies in the U.S. It is often used as a benchmark to gauge the overall performance of the stock market.

Conclusion
The stock market can seem complex at first, but understanding these basic concepts can help you make more informed decisions as an investor. Stocks give you the opportunity to profit from the growth of companies, either through capital gains or dividends. Remember to research, diversify your investments, and understand the risks involved in the stock market. By doing so, you can navigate the market with more confidence and make better investment choices.
"""


learnMore = '''
We could put learning information here

or in a different format if needed
'''

image = "lifeInvestIcon.png"

[[questions]]
question = "What does 'IPO' stand for?"
choices = [
  "Initial Public Offering",
  "Instant Purchase Order",
  "Investment Portfolio Option",
  "Internal Profit Objective"
]
answer = "Initial Public Offering"
why = 'IPO means "Initial Public Offering"'
difficulty = "easy"
reward = 100

[[questions]]
question = "If a stock splits 2-for-1, what happens to the share price (assuming all else equal)?"
choices = [
  "It doubles",
  "It halves",
  "It stays the same",
  "It drops to zero"
]
answer = "It halves"
why = "Stock splits increase the number of shares, but the value of the company stays the same, so the share price will be cut in half."
difficulty = "hard"
reward = 500

[[questions]]
question = "What does it mean to 'short' a stock?"
choices = [
  "Buy low, sell high",
  "Buy a stock and hold it",
  "Bet that the stock price will go down",
  "Avoid buying the stock"
]
answer = "Bet that the stock price will go down"
why = "Shorting a stock involves borrowing and selling it with the hope of buying it back at a lower price."
difficulty = "medium"
reward = 300

[[questions]]
question = "What is a dividend?"
choices = [
  "A fee for trading stocks",
  "An increase in stock price",
  "A share of company profits paid to shareholders",
  "A type of stock"
]
answer = "A share of company profits paid to shareholders"
why = "Dividends are payments made by a company to its shareholders from its profits."
difficulty = "easy"
reward = 150

[[questions]]
question = "Which index is commonly used as a benchmark for the U.S. stock market?"
choices = [
  "NASDAQ Composite",
  "Dow Jones Industrial Average",
  "S&P 500",
  "Russell 2000"
]
answer = "S&P 500"
why = "The S&P 500 is considered the best representation of the overall U.S. stock market."
difficulty = "medium"
reward = 250

[[questions]]
question = "What is market capitalization?"
choices = [
  "The value of a company's real estate",
  "The total value of all stocks on an exchange",
  "The total dollar value of a company’s outstanding shares",
  "The amount of cash a company holds"
]
answer = "The total dollar value of a company’s outstanding shares"
why = "Market cap is calculated by multiplying a company's stock price by its total number of outstanding shares."
difficulty = "medium"
reward = 250

[[questions]]
question = "What typically causes a stock’s price to rise?"
choices = [
  "Increased supply of shares",
  "Higher trading fees",
  "Positive news or strong earnings",
  "More regulations"
]
answer = "Positive news or strong earnings"
why = "Good news about a company often makes investors more willing to buy its stock, increasing demand and raising the price."
difficulty = "easy"
reward = 200

[[questions]]
question = "What does a 'bull market' refer to?"
choices = [
  "A market with low trading volume",
  "A market in which prices are falling",
  "A market in which prices are rising",
  "A market where investors are cautious"
]
answer = "A market in which prices are rising"
why = "A bull market refers to a sustained period of rising stock prices."
difficulty = "easy"
reward = 150

[[questions]]
question = "What is a P/E ratio?"
choices = [
  "Price of earnings per share",
  "Profit to equity ratio",
  "Price divided by earnings per share",
  "Performance/evaluation score"
]
answer = "Price divided by earnings per share"
why = "The price-to-earnings (P/E) ratio helps investors determine the market value of a stock compared to the company’s earnings."
difficulty = "medium"
reward = 300

[[questions]]
question = "What does diversification help with in investing?"
choices = [
  "Maximizing taxes",
  "Eliminating all risk",
  "Increasing fees",
  "Reducing investment risk"
]
answer = "Reducing investment risk"
why = "Diversifying spreads your investment across various assets, reducing the impact of any one failing."
difficulty = "easy"
reward = 200

[[questions]]
question = "What is an ETF?"
choices = [
  "A company that issues bonds",
  "An index fund that is traded like a stock",
  "A type of savings account",
  "A form of government loan"
]
answer = "An index fund that is traded like a stock"
why = "An ETF (Exchange-Traded Fund) tracks an index or sector and can be bought or sold on a stock exchange like individual stocks."
difficulty = "medium"
reward = 250

[[questions]]
question = "Which of the following best describes a stock?"
choices = [
  "A loan to a company",
  "A share in a company’s ownership",
  "A contract to buy a commodity",
  "A type of bank account"
]
answer = "A share in a company’s ownership"
why = "A stock represents a piece of ownership in a company and entitles the holder to a portion of its profits."
difficulty = "easy"
reward = 150

[[questions]]
question = "What does IPO stand for?"
choices = [
  "Initial Purchase Option",
  "Individual Price Offering",
  "Initial Public Offering",
  "Investor Payout Order"
]
answer = "Initial Public Offering"
why = "An IPO is when a company sells its shares to the public for the first time to raise capital."
difficulty = "easy"
reward = 150

[[questions]]
question = "What is the difference between a stock and a bond?"
choices = [
  "Stocks are debt; bonds are equity",
  "Stocks are short-term; bonds are long-term",
  "Stocks represent ownership; bonds represent a loan",
  "Stocks pay interest; bonds pay dividends"
]
answer = "Stocks represent ownership; bonds represent a loan"
why = "Stocks give you ownership in a company, while bonds are loans you give to a company or government that pay interest."
difficulty = "medium"
reward = 250

[[questions]]
question = "What does it mean when a stock is said to be 'volatile'?"
choices = [
  "It pays a high dividend",
  "Its price changes frequently and unpredictably",
  "It is not traded often",
  "It is highly regulated"
]
answer = "Its price changes frequently and unpredictably"
why = "Volatile stocks experience large price swings in short periods, often due to news, earnings, or speculation."
difficulty = "medium"
reward = 200

[[questions]]
question = "What is insider trading?"
choices = [
  "Buying shares from friends",
  "Trading stocks based on non-public information",
  "Investing in international markets",
  "Using a stockbroker for advice"
]
answer = "Trading stocks based on non-public information"
why = "Insider trading is illegal when someone uses confidential company information to gain an unfair market advantage."
difficulty = "hard"
reward = 400

[[questions]]
question = "Which type of stock typically pays regular dividends?"
choices = [
  "Growth stocks",
  "Penny stocks",
  "Preferred stocks",
  "Speculative stocks"
]
answer = "Preferred stocks"
why = "Preferred stocks usually pay fixed dividends and have priority over common stock in asset distribution."
difficulty = "medium"
reward = 250

[[questions]]
question = "What is a stockbroker?"
choices = [
  "A person who lends money to investors",
  "A person who trades stocks on behalf of investors",
  "An accountant for companies",
  "A regulator of the stock market"
]
answer = "A person who trades stocks on behalf of investors"
why = "Stockbrokers execute buy and sell orders for clients and may offer investment advice."
difficulty = "easy"
reward = 150

[[questions]]
question = "What is a limit order?"
choices = [
  "An order to buy or sell a stock at the current market price",
  "An order to hold a stock for a fixed time",
  "An order to buy or sell a stock only at a specific price or better",
  "An order that expires after a day"
]
answer = "An order to buy or sell a stock only at a specific price or better"
why = "Limit orders allow investors to control the price at which they buy or sell a stock."
difficulty = "medium"
reward = 250

[[questions]]
question = "What does volume mean in stock trading?"
choices = [
  "The price of a stock over time",
  "The number of shares traded during a period",
  "The interest rate of a stock",
  "The sound level of trading floors"
]
answer = "The number of shares traded during a period"
why = "Volume refers to how many shares of a stock are bought and sold during a specific time frame, indicating activity and liquidity."
difficulty = "easy"
reward = 150


